image: python:latest

# Change pip's cache directory to be inside the project directory since we can
# only cache local items.
variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

# before_script:
  # - python --version  # For debugging
  # - pip install virtualenv
  # - virtualenv venv
  # - source venv/bin/activate

test:
  script:
    - python -m unittest discover -s tests
